name: Bandit Security Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bandit-lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.4' # specify your project's Python version

      # Step 3: Install dependencies (Bandit and other requirements)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run Bandit on the codebase
      - name: Run Bandit Security Linter
        run: |
          bandit -r . -f txt -o bandit_report.txt

      # Step 5: Upload Bandit report as an artifact
      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.txt
